name: "Close stale issues"
on:
  schedule:
  - cron: "0 3 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}        
        stale-issue-label: stale 
        exempt-issue-labels: 'work in progress'
        only-labels: 'need more info'
        stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 30 days'
        close-issue-message: 'Automatically closed: no activity for 30 days after stale flag'
        stale-pr-message: none
        days-before-stale: 30
        days-before-close: 30
